### PR TITLE
Add Config support for different enviorements

### PR DESCRIPTION
**Pull request by amitaibu**
This PR will be moved to the original yeoman, but I work on it here for convenience. 

It adds most of the GitHub example from [Gizra/elm-spa-example](https://github.com/Gizra/elm-spa-example). On top of that, it adds the Config functionality from elm-hedley, that allows having different backends for different environments (e.g. the localhost will use the DEV, and the live site will use the LIVE backend)

elm

### CODE REVIEW

**Comment by amitaibu** [comment]
If we have no match for an environment, we will get this error message:

elm

**Comment by amitaibu** [comment]
@DavidHernandez ^^

**Comment by amitaibu** [comment]
Ready for review.

**Comment by DavidHernandez** [comment]
@amitaibu shouldn't we have a default environment and rely to it when there is no environment match?

**Comment by amitaibu** [comment]
I always prefer to have a big fail for sensitive stuff. Your config can have your client ID keys, backend URLs etc'. By being explicit about it, we know you won't miss it.

**Pull request merged**
